### ISSUE TITLE
DB empty, cannot parse JSON

### ISSUE THREAD

**Issue by f-hj** [ItsJimi/store-data#7]
```node
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at config.documents.forEach.document (/home/florian/project-back/node_modules/store-data/lib/index.js:28:36)
    at Array.forEach (native)
    at Object.init (/home/florian/project-back/node_modules/store-data/lib/index.js:22:22)
```

The DB file is empty.
```ls
-rw-rw-r-- 1 florian florian 0 avril 20 16:24 /tmp/conf.db
```

**Comment by f-hj** [comment]
Create backup of old file (timestamp?)
Recreate db (can be empty) to avoid err
